apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.backend.config.selector }}
  name: {{ .Values.serviceNames.backendService }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 8000
    protocol: TCP
    # Hard-coded in the application
    targetPort: 8000
  selector:
    app: {{ .Values.backend.config.selector }}
  type: {{ .Values.service.type}}
status:
  loadBalancer: {}
