apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentNames.frontendDeployment }}
  labels:
    app: {{ .Values.frontend.config.selector }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.config.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.config.selector }}
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Values.frontend.config.selector }}
        image: {{ .Values.frontend.image }}
        envFrom:
        - configMapRef:
            name: frontend-configmap
        resources:
          limits:
            cpu: "1000m"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 3000
          protocol: TCP