apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keyforge-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: minikube-ca
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    # Enables OpenTelemetry instrumentation
    nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
    nginx.ingress.kubernetes.io/otel-service-name: "ingress-nginx"
    nginx.ingress.kubernetes.io/otel-sampler-ratio: "1.0"
    nginx.ingress.kubernetes.io/otel-sampler: "AlwaysOn"
    nginx.ingress.kubernetes.io/otel-collector-host: "tempo.grafana.svc"
    nginx.ingress.kubernetes.io/otel-collector-port: "4317"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: ingress-cert
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.serviceNames.frontendService }}
                port:
                  number: 3000
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.serviceNames.backendService }}
                port:
                  number: 8000