x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},\d{3}) (?P<message>(?s:.*))$$'


services:
  prometheus:
    logging: *default-logging
  grafana:
    logging: *default-logging
  tempo:
    logging: *default-logging
  reverse-proxy:
    logging: *default-logging
  app-a:
    logging: *default-logging
  app-b:
    logging: *default-logging