services:
  reverse-proxy:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: nginx
    domainname: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/:/etc/nginx/ssl/
      - ./nginx/.htpasswd:/etc/apache2/.htpasswd
    environment:
      VITE_API_BASE_URL: https://nginx:443
    depends_on:
      - loki
    ports:
      - "443:443"
      - "80:80"
