{
 "title": "FastAPI Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "instance", "label": "Application", "query": { "query": "label_values(up,job)" } },
   { "name": "log_keyword", "label": "Log Query" },
   { "name": "status", "label": "Status-Code", "query": "2.*,3.*,4.*,5.*" }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime Status",
   "type": "gauge",
   "description": "Displays if the instance is up (1) or down (0).",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$instance\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{job=~\"$instance\", handler!=\"/metrics\", handler!=\"/utils/health-check\"}",
     "legendFormat": "{{methond}} {{handler}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=~\"$instance\",handler!=\"/metrics\", handler!=\"/utils/health-check\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Uptime Stat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{job=~\"$instance\"}",
     "legendFormat": "Uptime: {{job}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$instance\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Percent of (2|3|4|5)xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{job=~\"$instance\", status=~\"$status\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{job=~\"$instance\", handler!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "gauge",
   "description": "Shows the percentage of open file descriptors compared to the maximum allowed.",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$instance\"} / process_max_fds{job=~\"$instance\"} * 100",
     "legendFormat": "Percentage"
    },
    {
     "expr": "process_open_fds{job=~\"$instance\"}",
     "legendFormat": "Open files descriptors"
    },
    {
     "expr": "process_max_fds{job=~\"$instance\"}",
     "legendFormat": "Max opened files"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$instance\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "FastAPI Endpoint Performance",
   "type": "table",
   "description": "Displays average response time per endpoint, allowing developers to optimize specific routes.",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{job=~\"$instance\", handler!=\"none\"}[5m])) by (handler) / \nsum(rate(http_request_duration_seconds_count{job=~\"$instance\", handler!=\"none\"}[5m])) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(http_request_duration_seconds_sum{job=~\"$instance\"} / http_request_duration_seconds_count{job=~\"$instance\"})",
     "legendFormat": "{{method}} {{handler}} {{job}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Per Second",
   "type": "timeseries",
   "description": "his metric provides the rate of HTTP requests per second, allowing for tracking traffic patterns over time.",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=~\"$instance\"}[5m])",
     "legendFormat": "Endpoint - {{handler}} ; Job - {{job}}; Method - {{method}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=~\"$instance\",handler!=\"none\"} / http_request_duration_seconds_count{job=~\"$instance\"}",
     "legendFormat": "{{ handler }} {{job}}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{job=~\"$instance\", handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }} {{job}}"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=~\"$instance\"}[1m])",
     "legendFormat": "Endpoint - {{handler}} {{job}}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{job=~\"$instance\",handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }} {{job}}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{job=~\"$instance\",le=\"0.1\"}[1m]) \n/ ignoring (le) increase(http_request_duration_seconds_count{job=~\"$instance\"}[1m])",
     "legendFormat": "{{ handler }} {{job}}"
    }
   ]
  },
  {
   "title": "Backend Apps Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 40 },
   "targets": [
    {
     "expr": "{compose_service=~\"$instance\"} | pattern `<date> <time> <type> <logger> <code> [<_>=<trace_id> <_>=<span_id> <_>=<service_name>] - <msg>` | line_format \"{{.compose_service}}\\t{{.type}}\\t trace_id={{.trace_id}}\\t {{.msg}}\" |= \"$log_keyword\""
    }
   ]
  }
 ]
}